# Management ======================================================================================
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Spring ==========================================================================================
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:mem;mode=MySQL;database_to_lower=true
    username: sa
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  web:
    locale: en_US